config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  devise_for :users
  resources :tours do

    resources :bookings, only: [:new, :create]
    resources :reviews, only: :create
  end
  resources :bookings, only: [:destroy, :index, :update]
  get 'user/:id/tours', to: 'tours#personal_index', as: :ptours
  resources :users, only: [:show]
  # get 'user/bo', to: 'bookings#index', as: :ibookings
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :tour
  belongs_to :user
  validates :status, inclusion: { in: %w[Pending Accepted Declined] }
  validates :date, presence: true

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :tour

  validates :content, length: { minimum: 20 }, presence: true
  validates :user, presence: true
  validates :rating, presence: true

  def blank_stars
   5 - rating.to_i
  end
end

app/models/tour.rb
class Tour < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many :reviews, dependent: :destroy
  validates :name, presence: true
  validates :price, presence: true
  validates :description, presence: true
  validates :city, presence: true
  mount_uploader :photo, PhotoUploader
  geocoded_by :city
  after_validation :geocode, if: :will_save_change_to_city?

  include PgSearch
  pg_search_scope :search_by_city,
    against: [:city],
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  # has_many :bookings_as_guide, through: :tours, source: :bookings
  has_many :tours
  has_many :bookings
  has_many :reviews
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  mount_uploader :photo, PhotoUploader

  validates :first_name, presence: true
  validates :last_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  # [...]
  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: [:index, :personal_index],  unless: :skip_pundit?
  after_action :verify_policy_scoped, only: [:index, :personal_index], unless: :skip_pundit?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :photo])
  end
  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  skip_after_action :verify_authorized, only: :update
  def index
    @bookings = policy_scope(Booking)
  end

  def new
    @tour = Tour.find(params[:tour_id])
    authorize @tour
    @booking = Booking.new
    authorize @booking
  end

  def create
    @tour = Tour.find(params[:tour_id])
    authorize @tour
    @date = params[:booking][:date]
    @booking = Booking.new(date: @date, tour: @tour, user: current_user)
    authorize @booking
    if @booking.save
      redirect_to bookings_path
    else
      render :new
    end
  end

  def update
    @booking = Booking.find(params[:id])
    @booking.status = params[:status]
    @booking.save
    redirect_to ptours_path(current_user)
  end

  private

  def booking_params
    params.require(:booking).permit(:status, :date, :tour_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    skip_authorization
    @tour = Tour.find(params[:tour_id])
    @review = Review.new(review_params)
    @review.tour = @tour
    @review.user = current_user
    if @review.save
      respond_to do |format|
        format.html { redirect_to tour_path(@tour) }
        format.js  # <-- will render `app/views/reviews/create.js.erb`
      end
    else
      respond_to do |format|
        format.html { render 'tours/show' }
        format.js  # <-- idem
      end
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/controllers/tours_controller.rb
class ToursController < ApplicationController
  before_action :find_tour, only: [:show, :edit, :update, :destroy]
  skip_after_action :verify_policy_scoped, only: :index

  def index
    if params[:query].present?
      @tours = Tour.search_by_city(params[:query])
      @tours_for_map = @tours.where.not(latitude: nil, longitude: nil)
    else
      @tours = Tour.all
      @tours_for_map = @tours.where.not(latitude: nil, longitude: nil)
    end

    @markers = @tours_for_map.map do |tour|
      {
        lng: tour.longitude,
        lat: tour.latitude,
        # infoWindow: render_to_string(partial: "infowindow", locals: { tour: tour })
        image_url: helpers.asset_url('noun_Flag_2226775.png')
      }
    end
  end

  def personal_index
    @tours = policy_scope(Tour)
    @bookings = Booking.all.select { |booking| booking.tour.user == current_user }

    # @current_user_id = current_user.id.to_s
    # @tours = Tour.where(params[:user_id] = @current_user_id)
  end

  def show
    @booking = Booking.new
    @tour = Tour.find(params[:id])
    @review = Review.new

    @marker = [{
      lng: @tour.longitude,
      lat: @tour.latitude,
      image_url: helpers.asset_url('noun_Flag_2226775.png')
    }]
  end

  def new
    @tour = Tour.new
    authorize @tour
  end

  def edit
    authorize @tour
  end

  def create
    @tour = Tour.new(tours_params)
    authorize @tour
    @tour.user = current_user
    if @tour.save
      redirect_to tour_path(@tour)
    else
      render :new
    end
  end

  def update
    authorize @tour
    @tour.update(tours_params)
    redirect_to tour_path(@tour)
  end

  def destroy
    @tour.destroy
    redirect_to tours_path
  end

  private

  def tours_params
    params.require(:tour).permit(:name, :price, :description, :city, :photo)
  end

  def find_tour
    @tour = Tour.find(params[:id])
    authorize @tour
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @tours = @user.tours
    authorize @user
    authorize @tours
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<div class="container">
  <div class="dashboard">
    <div class="tabs">
      <%= link_to "My bookings", bookings_path, class: "tab active" %>
      <%= link_to "My tours", ptours_path(current_user), class: "tab" %>
    </div>
    <div class="scroll-box">
      <% @bookings.each do |booking| %>
        <% if booking.user == current_user %>
          <div class="message">
            <%= cl_image_tag booking.tour.user.photo, class: 'avatar-large' %>
            <div class="message-name">
              <h3><%= booking.tour.user.first_name %></h3>
              <p><%= booking.date %></p>
            </div>
            <div class="message-body">
              <p><strong><%= booking.tour.name %></strong></p>
              <p>
                <%= booking.tour.description %>
              </p>
            </div>
            <div class="message-status">
              <p class="status <%= booking.status.downcase %>"><%= booking.status %></p>
              <p class="price"><%= booking.tour.price %>€</p>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Inconsolata" rel="stylesheet">
    <title>AirTournGuide</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>

    <%= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <div class="wrapper">
      <%= render 'shared/navbar' %>
      <%= render 'shared/flashes' %>
      <%= yield %>
      <%= render 'shared/footer' %>
    </div>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(74,180,205,0.5)), url(https://images.unsplash.com/photo-1484544808355-8ec84e534d75?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=766&q=80);">

  <div class="birdyy">

      <div class="bird-container bird-container--one">
    <div class="bird bird--one"></div>
  </div>

  <div class="bird-container bird-container--two">
    <div class="bird bird--two"></div>
  </div>

  <div class="bird-container bird-container--three">
    <div class="bird bird--three"></div>
  </div>

  <div class="bird-container bird-container--four">
    <div class="bird bird--four"></div>
  </div>

  <div class="container text-center">

<h1>Discover places in a new way!</h1>
          <p>Visit <span id="banner-typed-text2"></span>like a <span id="banner-typed-text">local!</span></p>
    <div class="text-left">
      <div class="formbar">
      <%= form_tag tours_path, method: :get do %>
        <%= text_field_tag :query,
          params[:query],
          class: "form-control",
          placeholder: "Find a city"
        %>
      <% end %>
      </div>
    </div>
    </div>
  </div>

</div>

<div class="container">
  <h1 class="text-center">Check the latest tours </h1>
  <% @tours = Tour.all.first(4) %>
  <div class="row">
    <% @tours.each do |tour| %>
      <div class="col-xs-6 col-sm-3">
        <%= render 'shared/cards', tour: tour %>
      </div>
    <% end %>
  </div>
</div>

app/views/reviews/_form.html.erb
<%= simple_form_for([ tour, review ], remote: true) do |form| %>
  <%= form.input :rating, collection: (1..5).to_a, label: "Rate your experience" %>
  <%= form.input :content, as: :text %>
  <%= form.button :submit %>
<% end %>

app/views/reviews/_show.html.erb
<h3>
  <%= review.user.first_name %><% review.rating.to_i.times do  %>
    <i class="fas fa-star"></i>
  <% end %>
  <% review.blank_stars.times do %>
    <i class="far fa-star"></i>
  <% end %>
</h3>
<p class="border"><%= review.content %></p>

app/views/reviews/create.js.erb
function refreshForm(innerHTML) {
  const newReviewForm = document.getElementById('new_review');
  newReviewForm.innerHTML = innerHTML;
}

function addReview(reviewHTML) {
  const reviews = document.getElementById('review');
  reviews.insertAdjacentHTML('beforeend', reviewHTML);
}

<% if @review.errors.any? %>
  refreshForm('<%= j render "reviews/form", tour: @tour, review: @review %>');
<% else %>
  addReview('<%= j render "reviews/show", review: @review %>');
  refreshForm('<%= j render "reviews/form", tour: @tour, review: Review.new %>');
<% end %>

app/views/shared/_cards.html.erb
<div class="blog-card" style="background-image:url(
  <% if tour.photo.present? %>
    '<%= cl_image_path tour.photo, height: 220, width: 190, crop: :lfill %>'
  <% else %>
    '<%= cl_image_path "https://loremflickr.com/320/240/#{tour.city}", height: 220, width: 100, crop: :lfill %>'
  <% end %>)">
  <div class="title-content">
    <h3><%= tour.name.capitalize %></h3>
    <hr />
    <div class="intro"><i class="fas fa-map-pin"></i> <%= tour.city.capitalize %></div>
  </div><!-- /.title-content -->
  <div class="card-info">
    <%= tour.description[0..40] %>
  </div><!-- /.card-info -->
  <div class="utility-info">
    <ul class="utility-list">
      <li><i class="fas fa-euro-sign"></i><%= tour.price %></li>
      <li><%= link_to user_path(tour.user) do %><%= cl_image_tag tour.user.photo, width: 25, height: 25, crop: :thumb,class: 'card-trip-user avatar'%> <% end %></li>
    </ul>
  </div><!-- /.utility-info -->
  <!-- overlays -->
  <div class="gradient-overlay"></div>
  <div class="color-overlay"></div>
  <%= link_to "", tour_path(tour), class: "card-link" %>
</div><!-- /.blog-card -->

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="https://github.com/jlsrvr/-airtournguide"><i class="fab fa-github"></i></a>
  </div>
  <div class="footer-copyright">
    This website is made with <i class="fas fa-heart"></i> by BeachPlease <i class="fas fa-umbrella-beach"></i>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png", width: 150 %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <%= link_to "Tours", tours_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Create a tour", new_tour_path , class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Dashboard", bookings_path, class: "navbar-wagon-item navbar-wagon-link" %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= cl_image_tag current_user.photo, width: 40, height: 40, crop: :thumb, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to edit_user_registration_path do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Sign in"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to t(".sign_up", default: "Sign up"), new_user_registration_path, class: "navbar-wagon-item navbar-wagon-link" %>
          <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <% if user_signed_in? %>
    <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li>
          <%= link_to edit_user_registration_path do %>
            <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
          <% end %>
        </li>
        <li><%= link_to t("#", default: "Tours"), tours_path, class: "navbar-wagon-item navbar-wagon-link" %></li>
        <li><%= link_to t("#", default: "Create a tour"), new_tour_path, class: "navbar-wagon-item navbar-wagon-link" %></li>
        <li><%= link_to t("#", default: "Dashboard"), bookings_path, class: "navbar-wagon-item navbar-wagon-link" %></li>
        <li>
          <%= link_to destroy_user_session_path, method: :delete do %>
            <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
          <% end %>
        </li>
      </ul>
      </div>
    </div>
  <% else %>
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><%= link_to t(".sign_in", default: "Sign in"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %></li>
        <li><%= link_to t(".sign_up", default: "Sign up"), new_user_registration_path, class: "navbar-wagon-item navbar-wagon-link" %></li>
      </ul>
    </div>
  </div>
  <% end %>
</div>

app/views/tours/_form_tour.html.erb
<div class="container form">
  <div class="row">
    <div class="col-xs-6">
      <%= simple_form_for(@tour) do |f| %>
        <%= f.input :name %>
        <%= f.input :description %>
    </div>
    <div class="col-xs-6">
        <%= f.input :city %>
        <%= f.input :price %>
    </div>
  </div>
  <div class="row text-center">
        <%= f.input :photo, input_html: { class: 'hidden', id: 'photo-input'}, label_html: { class: 'upload-photo'}, label: '📷 Upload a photo' %>
        <%= f.input :photo_cache, as: :hidden %>
        <%= image_tag "", width: 300, class: "hidden", id: "photo-preview" %>
    <div class="form-actions">
      <%= f.button :submit %>
    </div>
    <% end %>
  </div>
</div>

app/views/tours/edit.html.erb
<%= render 'form_tour', tour: @tour %>

app/views/tours/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-6 col-sm-3">
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1513736302339-d4d0335c0fb5?ixlib=rb-1.2.1&auto=format&fit=crop&w=750&q=80)">
          <p><%= link_to "PARIS", :controller => "tours", :query => "Paris" %></p>
      </div>
    </div>
    <div class="col-xs-6 col-sm-3">
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1508710985089-e985fabbb184?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1300&q=80)">
          <p><%= link_to "LONDON", :controller => "tours", :query => "London" %></p>
      </div>
    </div>
    <div class="col-xs-6 col-sm-3">
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1511322896738-1216428a1b1e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=750&q=80)">
          <p><%= link_to "VENEZIA", :controller => "tours", :query => "Venezia" %></p>
      </div>
    </div>
    <div class="col-xs-6 col-sm-3">
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1539037116277-4db20889f2d4?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=750&q=80)">
        <p><%= link_to "BARCELONA", :controller => "tours", :query => "Barcelona" %></p>
      </div>
    </div>
  </div>
  <h1 class="text-center"><strong>Tours around the world</strong></h1>
</div>

<div class="text-left">
  <div class="formbar">
  <%= form_tag tours_path, method: :get do %>
    <%= text_field_tag :query,
      params[:query],
      class: "form-control",
      placeholder: "Find a city"
    %>
  <% end %>
  </div>
</div>

<div id = "my-flex">
  <div class="cards">
    <div class="row">
      <% @tours.each do |tour| %>
        <div class="col-xs-12 col-sm-6 col-md-4">
          <%= render 'shared/cards', tour: tour %>
        </div>
      <% end %>
    </div>
  </div>
  <div
   id="map"
   style="width: 100%;
   height: 600px;"
   data-markers="<%= @markers.to_json %>"
   data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
  ></div>
</div>

app/views/tours/new.html.erb
<%= render 'form_tour', tour: @tour %>

app/views/tours/show.html.erb
<div class="banner-show"
  style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url(
    <% if @tour.photo.present? %>
     '<%= cl_image_path @tour.photo, height: 372, crop: :fill %>'
    <% else %>
      '<%= cl_image_path "https://images.unsplash.com/photo-1532154066703-3973764c81fe?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=334&q=80" %>'
    <% end %> );">

  <div class="container text-center">
    <h1><%= @tour.name %></h1>
    <p>A tour in <%= @tour.city.capitalize %>, with <%= @tour.user.first_name.capitalize %></p>
  </div>
</div>

<% if @tour.user != current_user %>
  <div class="container tour">
    <div class="col-xs-6" >
      <div class="text-center">
        <h4 class="title">Tour description
          <% if policy(@tour).update? %>
            <%= link_to edit_tour_path do %>
              <i class="fas fa-edit"></i>
            <% end %>
          <% end %>
          <% if policy(@tour).destroy? %>
            <%= link_to tour_path, method: :delete, data: { confirm: "Are you sure?" } do %>
              <i class="fas fa-trash-alt">
              </i>
            <% end %>
          <% end %>
        </h4>
        <div class="p-showtour">
          <p><%= @tour.description %></p>
          <p><%= @tour.city %> <br> <%= @tour.price %>€</p>
        </div>
      <div id="Calendar">
        <h4 class= "title">Choose a day</h4>
        <div class="form-wrapper" style="width: 200px; margin: 0 auto;">
          <%= simple_form_for [@tour, @booking], url: tour_bookings_url(@tour) do |f| %>
            <%= f.input :date, label: false, as: :string, required: false, input_html: {class: "datepicker"} %>
            <%= f.button :submit, "Book", class: "btn btn-yours" %>
          <% end %>
        </div>
      </div>
    </div>
      <div class="text-center" id="Guide">
        <h4 class= "title">Guide</h4>

        <%= cl_image_tag @tour.user.photo, width: 50, height: 50, crop: :thumb, class: 'avatar guide' %>

        <br>
        <p> <%= @tour.user.first_name %> </p>
      </div>
  </div>
    <div class="col-xs-6">
      <div
        id="map"
        style="width: 100%;
        height: 500px;
        "
        data-markers="<%= @marker.to_json %>"
        data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
      ></div>
    </div>
  </div>
  <div class="container reviews">
    <div class="row">
      <h2>
        <%= pluralize @tour.reviews.size, "review" %>
      </h2>
      <div id="reviews">
          <% if @tour.reviews.blank? %>
            Be the first to leave a review for <%= @tour.name %>
            <%= render 'reviews/form', tour: @tour, review: Review.new %>
          <% else %>
          <div class="row">
            <div class="col-xs-6">
              <%= render 'reviews/form', tour: @tour, review: Review.new %>
            </div>
            <div id="review" class="col-xs-6">
            <% @tour.reviews.each do |review| %>
              <%= render 'reviews/show', review: review %>
            <% end %>
            </div>
          </div>
          <% end %>
      </div>
    </div>
  </div>
<% else %>
  <div class="container">
    <div class="row">
      <div class="col-xs-6 text-center description">
        <h4 class="title">Tour description
          <% if policy(@tour).update? %>
            <%= link_to edit_tour_path do %>
              <i class="fas fa-edit"></i>
            <% end %>
          <% end %>
          <% if policy(@tour).destroy? %>
            <%= link_to tour_path, method: :delete, data: { confirm: "Are you sure?" } do %>
              <i class="fas fa-trash-alt">
              </i>
            <% end %>
          <% end %>
        </h4>

        <div class="p-showtour">
          <p><%= @tour.description %></p>
          <p><%= @tour.city.capitalize %> <br> <%= @tour.price %>€</p>
        </div>
        <div class="text-center" id="Guide">
          <h4 class= "title">Guide</h4>

          <%= cl_image_tag @tour.user.photo, width: 50, height: 50, crop: :thumb, class: 'avatar guide' %>
          <br>
          <p> <%= @tour.user.first_name %> </p>
        </div>
      </div>
      <div class="col-xs-6">
        <div
          id="map"
          style="width: 100%;
          height: 500px;
          "
          data-markers="<%= @marker.to_json %>"
          data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
        ></div>
      </div>
    </div>
  </div>
  <div class="container reviews guide">
    <div class="row">
      <h2>
        <%= pluralize @tour.reviews.size, "review" %>
      </h2>
      <div id="reviews">
            <% @tour.reviews.each do |review| %>
              <%= render 'reviews/show', review: review %>
            <% end %>
      </div>
    </div>
  </div>
<% end %>